"use client";
import { useState } from "react";
//import type { Metadata } from "next";
import { Providers } from "./providers";
import "./globals.css";
import NavBar from "../components/NavBar";

//export const metadata: Metadata = {
//title: "Create Next App",
//description: "Generated by create next app",
//};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <html lang="en">
      <body
        className={`min-h-screen w-full bg-default-50 text-default-900 ${darkMode == true ? "dark" : ""} `}
      >
        <Providers>
          <NavBar darkMode={darkMode} setDarkMode={setDarkMode} />
          {children}
        </Providers>
      </body>
    </html>
  );
}
