import type { Metadata } from "next";
import { Providers } from "./providers";
import "./globals.css";
import NavBar from "../components/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex w-full flex-col items-center justify-center bg-default-50 text-default-900 dark">
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
