const baseUrl = "https://api.jikan.moe/v4";
export const topAnimeUrl = `${baseUrl}/top/anime`;
export const topMangaUrl = `${baseUrl}/top/manga`;
export const topCharactersUrl = `${baseUrl}/top/characters`;
export const topPeopleUrl = `${baseUrl}/top/people`;
export const animeUrl = `${baseUrl}/anime`;
export const mangaUrl = `${baseUrl}/manga`;
export const charactersUrl = `${baseUrl}/characters`;
export const peopleUrl = `${baseUrl}/people`;
export const genresUrl = `${baseUrl}/genres/anime`;
export const promosUrl = `${baseUrl}/watch/promos`;
export const recentEpisodesUrl = `${baseUrl}/watch/episodes`;
export const popularEpisodesUrl = `${recentEpisodesUrl}/popular`; // /watch/episodes/popular
export const seasonUrl = `${baseUrl}/seasons`;
export const seasonNowUrl = `${seasonUrl}/now`;
export const newEpisodesUrl = `${baseUrl}/watch/episodes`;
